// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guazvksqzlxfvdgzpyfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YXp2a3Nxemx4ZnZkZ3pweWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDc5MjIsImV4cCI6MjA3NDU4MzkyMn0.7aCXWcpn5XARghrhbwwSZK1dnv1qv1muycG7O7UwpPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});